"""Add is_aggregated and aggregated_at in ProductUniqueCode model

Revision ID: 36eaa6b0d057
Revises: 63f23d7ee1a0
Create Date: 2024-02-14 12:57:31.047929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36eaa6b0d057'
down_revision: Union[str, None] = '63f23d7ee1a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
