"""Add ProductUniqueCode

Revision ID: 63f23d7ee1a0
Revises: af373c332057
Create Date: 2024-02-12 20:17:39.163861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63f23d7ee1a0'
down_revision: Union[str, None] = 'af373c332057'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
